services:
  attctrl:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=${APP_PORT:-9898}
        - APP_TIMEZONE=${APP_TIMEZONE:-"UTC"}
    container_name: "attctrl"
    restart: always
    env_file:
      - .env
    ports:
      - "${APP_PORT:-9898}:${APP_PORT:-9898}"
    volumes:
    - attctrl_data:/app/data
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro

volumes:
  attctrl_data:
    name: attctrl_data
